{% set name = "argo-models" %}
{% set version = "2.6.3.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7bf25c1a9f9f939dfa1262bc8f81bb9a618f05e0dc3d16424cbc67ac42f3166

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - argo
    - argo.models

about:
  home: https://github.com/e2fyi/argo-models
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Generated openapi models for Argo objects.
  description: |
    argo-models is a argo namespaced package with the argo.models subpackage
    which contains the generated OpenAPI models from Argo.

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
