{% set name = "argo-models" %}
{% set version = "2.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26162327e360627cf806223f6b2bb26fbfc7c9b66e1e056ba7101f114f4048e8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - argo
    - argo.models

about:
  home: https://github.com/e2fyi/argo-models
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Generated openapi models for Argo objects.
  description: |
    argo-models is a argo namespaced package with the argo.models subpackage
    which contains the generated OpenAPI models from Argo.

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
