travis:
  secure:
    BINSTAR_TOKEN: CKuJLQNbEeerZIA6xhfvvW1KI1EkmFBCkaYrf8IhwM/hoTXVY1umIQbH3aRIafTyAkCApErguUPUFbSgqcjhExm8/ArZanRR2FmspOmYUbhhNqEKi3KmOUOyjhyXGZRdfkW0KrArCKCTn0WRpCV2lsA0bZuKm9uSUvNBUlyQKNuVUTJy1x8JSXlCJUKLQmUN7cePlsKrXe++uY7r/0yHjAbUumfg/1R7uVmirjeSAn/kW4GIuQ0dw5JSGlsoNDwwohmhDtRC2VuWjsb2OsRIEwgxMawDmow1gy987PZ+E6qJ47BewzDygAp+zB26TJdlahPJjEqBYMKRDxpTwRM2iL6J0gNx84j796mdZ1c3XwIFdH/VHAMCR5Z8S4ux3/x47m4H3Wb5TTnyIscdAFY7U7MNwBdWXUtOOQFQrpkW3OIEz6bNujMjHjwfFqG4emHdh5nagDUhhCSosBoAfJ0K3mAPtrMe2JyUVLJsVoUzfsSUrG934AGTtb45muV5hSa1wO+jQX2/Xbdi1LvqsO4aVdWp7JWDjWFVO6mrQLmG2/3wwBc+W0Z+wGyvnWu/pZXqFzpAbAkKxCo+9kmWgvYJcQJ4JRaRKCLfDk4xxCAJ2SYd3H5n2kW3iSrecJv135kXk/6PuxtGGUiEhLYirQ4gYvbNAS3WzKbChjPTYtCIvMA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
